### ISSUE TITLE
Hello , I have a question and I am really desire to get a reply

### ISSUE THREAD

**Issue by Mahiro2211** [thaiminhpv/RelaHash#1]
Thank you for sharing the code, and these days I have been trying to test Relahash's performers in another dataset, I found that in the "labels_scaled"  part, It will be easy to get a NAN loss,
```python
    def forward(self, logits, z, labels):
        if self.multiclass:
            if not self.one hot:
                labels = F.one_hot(labels, logits.size(1))
            labels = labels.float()

            margin_logits = self.compute_margin_logits(logits, labels)

            # label smoothing
            log_logits = F.log_softmax(margin_logits, dim=1)
            labels_scaled = labels/labels.sum(dim=1, keepdim=True)  # that is place
            loss = - (labels_scaled * log_logits).sum(dim=1)
            loss = loss.mean()
```
The way I came across this question was during my attempt to identify the main cause of the NAN loss. Throughout this process, I have preserved every output variable, such as log_logits and labels_scaled. Upon closer examination, I discovered that there are some Nan values in the labels_scaled output. I believe this discrepancy may be attributed to an incompatibility between my model and yours.

To elaborate, if I don't consider a large loss to be problematic, I could potentially remove the labels_scaled part without significantly impacting the model's performance. This is the most straightforward solution I can currently think of.

In my efforts to mitigate any negative effects, I have attempted to use the loss_scaled approach by utilizing the apex package from https://github.com/NVIDIA/apex. However, I am uncertain whether my approach is correct or entirely misguided. Therefore, I would greatly appreciate your feedback on the matter or any appropriate solutions you may provide.

Thank you sincerely,
An individual from China with limited proficiency in English. 🙏

**Comment by Mahiro2211** [comment]
Here is the information regarding label_scaled for your reference. Thank you very much for your attention and reading.
![image](https://github.com/thaiminhpv/RelaHash/assets/130811701/563d06d1-c943-458d-ba44-e6bc738746cf)

**Comment by Mahiro2211** [comment]
I used it on my model I found that it is a so excellent project, in that I get 0.1 more mAP compared to the previous model

**Comment by thaiminhpv** [comment]
Thank you for reaching out to me.

As your code reaches there, I assume that you are working with a **multilabel** dataset. I think the problem may arise when there are some samples in your dataset do not have any classes (labels).

```python
labels_scaled = labels/labels.sum(dim=1, keepdim=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If some samples have no labels, then `labels.sum(dim=1, keepdim=True)` will have some `0` elements, resulting in `ZeroDivisionError: division by zero`. I believe the error is suppressed and becomes `NaN`.

Hope this answers your question.
